# Generated by Django 4.2.4 on 2023-08-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_id', models.IntegerField(unique=True)),
                ('woocommerce_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsoleMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_domain', models.CharField(max_length=255)),
                ('store_path', models.CharField(max_length=255)),
                ('erp_server_ip', models.CharField(max_length=255)),
                ('erp_server_port', models.CharField(max_length=255)),
                ('erp_username', models.CharField(max_length=255)),
                ('erp_password', models.CharField(max_length=255)),
                ('woo_consumer_key', models.CharField(max_length=255)),
                ('woo_consumer_secret', models.CharField(max_length=255)),
            ],
        ),
    ]
