# Generated by Django 4.2.4 on 2023-09-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyramidWebConnector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consolemessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
