# Generated by Django 4.2.4 on 2023-09-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyramidWebConnector', '0003_rename_erp_server_port_useranswer_ftp_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='woo_consumer_secret',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
