# Generated by Django 4.2.4 on 2023-09-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyramidWebConnector', '0004_useranswer_woo_consumer_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='erp_server_port',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='last_revision_number',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
