# Generated by Django 4.2.4 on 2023-09-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyramidWebConnector', '0005_useranswer_erp_server_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymapping',
            name='erp_id',
            field=models.CharField(max_length=255),
        ),
    ]
