# Generated by Django 4.2.4 on 2023-09-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyramidWebConnector', '0006_alter_categorymapping_erp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymapping',
            name='woocommerce_id',
            field=models.IntegerField(),
        ),
    ]
