# Generated by Django 4.2.4 on 2023-09-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyramidWebConnector', '0007_alter_categorymapping_woocommerce_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymapping',
            name='erp_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='categorymapping',
            name='woocommerce_id',
            field=models.IntegerField(null=True),
        ),
    ]
